language: bash

os: 
  - linux
  - osx

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - sudo apt-get -y install zsh

script:
  - bash travis.sh
